### ISSUE TITLE
Initialize the Database

### ISSUE THREAD

**Issue by tborsa** [alumni-lab/dave-s-netflix#4]
Setup Django with sql lite

- [ ] Modularize sql client connection
- [ ] Create migrations for the initial schema according to the ERD
- [ ] Create initial Seed data

**Comment by benjdelt** [comment]
Started working on the issue on [this branch](https://github.com/alumni-lab/dave-s-netflix/tree/ben/initialize-db). There is a foreign key clash that will be resolved by using the related name parameter [as showed here](https://stackoverflow.com/questions/22538563/django-reverse-accessors-for-foreign-keys-clashing). Before continuing, I'll read about django's built-in User model and see how I can extend it instead of replacing it.

**Comment by tborsa** [comment]
Thanks for the update.
